Add config options for running behind proxies and with NAT
systemli/ansible-role-jitsi-meet pull request #50
Opened 2021-02-20 19:40 UTC by felinira

This adds config options to allow for operation in a NAT'ed environment with a proxy that does SSL termination at the network border.

2021-02-22 11:44 UTC, xshadow requested changes
Thanks for your PR. Please change the variable names accordingly.

2021-02-22 11:44 UTC, xshadow commented on defaults/main.yml
> +jitsi_meet_nginx_listen_https: true
Please change the variables to `jitsi_meet_nginx_listen_https_enabled`

2021-02-22 11:44 UTC, xshadow commented on defaults/main.yml
> +jitsi_meet_behind_nat: false
Please change the variables to `jitsi_meet_behind_nat_enabled`

2021-02-23 18:10 UTC, felinira commented
Done. Thanks for developing the role, it makes deploying jitsi really simple! I also configured the node exporter and grafana dashboards and they are really nice too :)

2021-02-23 19:37 UTC, merged